name: ci
on: [push, pull_request]
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          profile: minimal
          toolchain: nightly
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            components: clippy
            override: true
            toolchain: nightly
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
        with:
          skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: "bernardo"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: nix-build
        run: "nix-build"

  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
        with:
          skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: "bernardo"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: nixpkgs-fmt
        run: "nix-shell --run 'nixpkgs-fmt --check .'"
